server:
  port: 8089
  servlet:
    path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: 123456


#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mysql?useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化连接数
#      initial-size: 5
#      #最小空闲连接
#      min-idle: 5
#      #最大活动连接
#      max-active: 20
mybatis:
  type-aliases-package: com.hp.entity